[package]
name = "lace-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitflags = "2.11.0"
lace-util = { version = "0.1.0", path = "../lace-util", default-features = false }
lace-util-derive = { version = "0.1.0", path = "../lace-util-derive" }
spin = "0.10.0"
uefi = { version = "0.36.1", features = ["global_allocator", "panic_handler"], optional = true }
uefi-raw = { version = "0.13.0", optional = true }

[features]
default = ["mock"]
efi = ["dep:uefi", "dep:uefi-raw"]
mock = []
