# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
version: 2
updates:
  # Monitor root Cargo workspace
  # This will monitor the workspace members defined in the root Cargo.toml.
  # Note: ulib/ is not monitored as it contains no external dependencies.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
