# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(ulib|data/hwids)/
      - id: end-of-file-fixer
        exclude: ^(ulib|data/hwids)/
      - id: check-yaml
        exclude: ^(ulib|data/hwids)/
      - id: check-toml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code with rustfmt
        entry: ./scripts/cargo_ci.py fmt --all
        language: system
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.19.0
    hooks:
      - id: cargo-deny
        args: ["--all-features", "check"]
