# SPDX-License-Identifier: GPL-2.0+
[workspace]
resolver = "2"
members = [
    "lace-platform",
    "lace-stubble",
    "lace-util",
    "lace-util-derive",
    "tools/collect-hwids",
    "tools/fakeedid",
    "tools/pewrap",
    "tools/xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only OR GPL-3.0-only"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
