# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
[workspace]
resolver = "2"
members = [
    "lace-platform",
    "lace-stubble",
    "lace-util",
    "lace-util-derive",
    "tools/collect-hwids",
    "tools/fakeedid",
    "tools/pewrap",
    "tools/xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only OR GPL-3.0-only"

[workspace.dependencies]
bitflags = "2.11.0"
clap = { version = "4.6.0", features = ["derive", "wrap_help"] }
clap_mangen = "0.2"
fdt = { version = "0.1.5", default-features = false }
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
spin = "0.10.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
uefi = { version = "0.37.0" }
uefi-raw = { version = "0.14.0" }
zerocopy = "0.8.47"
zip = { version = "8.4.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
