[package]
name = "lace-util"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fdt.workspace = true
lace-util-derive = { path = "../lace-util-derive" }
zerocopy = { workspace = true, features = ["derive"] }

[features]
default = ["std", "grub"]
std = []
grub = []
