[package]
name = "lace-util"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fdt.workspace = true
lace-util-derive = { path = "../lace-util-derive" }
libc = { workspace = true, optional = true }
zerocopy = { workspace = true, features = ["derive"] }

[features]
default = ["firmware", "std", "grub"]
firmware = []
std = ["dep:libc"]
grub = []
