[package]
name = "lace-stubble"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lace-util = { version = "0.1.0", path = "../lace-util", default-features = false }
lace-platform = { version = "0.1.0", path = "../lace-platform", default-features = false }
uefi = { version = "0.36.1", optional = true }

[features]
default = ["mock"]
efi = ["lace-platform/efi", "dep:uefi"]
mock = ["lace-platform/mock"]
