[package]
name = "lace-stubble"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lace-util = { path = "../lace-util", default-features = false }
lace-platform = { path = "../lace-platform", default-features = false }
log.workspace = true
uefi = { workspace = true, optional = true }

[features]
default = ["mock"]
efi = ["lace-platform/efi", "dep:uefi"]
bios = ["lace-platform/bios"]
mock = ["lace-platform/mock"]
