[package]
name = "lace-stubble"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only OR GPL-3.0-only"

[dependencies]
lace-util = { version = "0.1.0", path = "../lace-util", default-features = false }
lace-platform = { version = "0.1.0", path = "../lace-platform", default-features = false }
uefi = { version = "0.36.1", optional = true }

[features]
default = ["mock"]
efi = ["lace-platform/efi", "dep:uefi"]
mock = ["lace-platform/mock"]
