[package]
name = "virt-bootblock"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only OR GPL-3.0-only"

[dependencies]
lace-drivers = { path = "../../../../lace-drivers", default-features = false }
lace-util = { path = "../../../../lace-util", default-features = false }
linked_list_allocator = "0.10.5"
spin = "0.10.0"
zerocopy = { version = "0.8.48", features = ["derive"] }

[features]
