# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
clap_mangen.workspace = true

# Tool dependencies for generating man pages
pewrap = { path = "../pewrap" }
collect-hwids = { path = "../collect-hwids" }
