[package]
name = "pewrap"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only OR GPL-3.0-only"

[dependencies]
clap = { version = "4.5.58", features = ["derive", "wrap_help"] }
lace-util = { version = "0.1.0", path = "../../lace-util" }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
zerocopy = "0.8.39"
